### Register a user
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "name": "Binamra Lamsal",
  "email": "binamralamsal@gmail.com",
  "password": "1"
}

### Login a user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "binamralamsal@gmail.com",
  "password": "123456"
}